In [1]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

In [2]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

### 데이터 탐색

In [3]:
import pandas as pd

df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
df.head()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [4]:
cancer.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
df_target = pd.Series(cancer.target)

In [8]:
df_target.value_counts()

1    357
0    212
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [5]:
df.describe()

mean radius  mean texture  ...  worst symmetry  worst fractal dimension
count   569.000000    569.000000  ...      569.000000               569.000000
mean     14.127292     19.289649  ...        0.290076                 0.083946
std       3.524049      4.301036  ...        0.061867                 0.018061
min       6.981000      9.710000  ...        0.156500                 0.055040
25%      11.700000     16.170000  ...        0.250400                 0.071460
50%      13.370000     18.840000  ...        0.282200                 0.080040
75%      15.780000     21.800000  ...        0.317900                 0.092080
max      28.110000     39.280000  ...        0.663800                 0.207500

[8 rows x 30 columns]

### 데이터 준비 (특성 스케일링, 훈련/테스트 데이터 분리)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
cancer_scaled = sc.fit_transform(cancer.data)

X_train, X_test, y_train, y_test = train_test_split(cancer_scaled, cancer.target, test_size=0.3)

### 이진 분류기 선택 / 학습

In [7]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_preds = lr.predict(X_test)
lr_proba = lr.predict_proba(X_test)[:, 1]

In [8]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

def evaluation(y_test, pred=None, pred_proba=None):
    confusion = confusion_matrix(y_test, pred)
    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)
    roc_auc = roc_auc_score(y_test, pred_proba)
    print('오차 행렬')
    print(confusion)
    print('정확도 : {0:.4f} 정밀도 {1:.4f} 재현율 {2:.4f} F1 {3:.4f} AUC {4:.4f}\n'.format(accuracy, precision, recall, f1, roc_auc))

In [9]:
evaluation(y_test, lr_preds, lr_proba)

오차 행렬
[[ 54   6]
 [  0 111]]
정확도 : 0.9649 정밀도 0.9487 재현율 1.0000 F1 0.9737 AUC 0.9967



### 그리드 서치를 통해서 규제 강도를 tuning (l1, l2, alpha)


In [10]:
from sklearn.model_selection import GridSearchCV

param = {
    'penalty': ['l1', 'l2'],
    'C': [0.01, 0.05, 0.1, 1, 5, 10]
}

lr_clf = LogisticRegression(solver='liblinear')
grid_clf = GridSearchCV(lr_clf, param_grid=param, scoring='accuracy', cv=5)
grid_clf.fit(X_train, y_train)
print('최적 하이퍼 파라미터 : {0}, 최적 평균 정확도 {1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))

최적 하이퍼 파라미터 : {'C': 0.1, 'penalty': 'l2'}, 최적 평균 정확도 0.985


In [11]:
best_model = grid_clf.best_estimator_

y_pred = best_model.predict(X_test)
y_pred_proba = best_model.predict_proba(X_test)[:, 1]

In [12]:
evaluation(y_test, y_pred, y_pred_proba)

오차 행렬
[[ 55   5]
 [  0 111]]
정확도 : 0.9708 정밀도 0.9569 재현율 1.0000 F1 0.9780 AUC 0.9964



### 최종

In [13]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

def scale(method='None', X_train=None, X_test=None):
    if method == 'Standard':
        sc = StandardScaler()
        X_scaled_train = sc.fit_transform(X_train)
        X_scaled_test = sc.transform(X_test)
    elif method == 'MinMax':
        mm = MinMaxScaler()
        X_scaled_train = mm.fit_transform(X_train)
        X_scaled_test =mm.transform(X_test)
    elif method == 'Log':
        X_scaled_train = np.log1p(X_train)
        X_scaled_test = np.log1p(X_test)
    else:
        X_scaled_train = X_train
        X_scaled_test = X_test
    return X_scaled_train, X_scaled_test

In [14]:
def Search(model, X_train, X_test, y_train, y_test, params):
    grid_clf = GridSearchCV(model, param_grid=params, scoring='accuracy', cv=5)
    grid_clf.fit(X_train, y_train)
    print('최적 하이퍼 파라미터 : {0}, 최적 평균 정확도 {1:.3f}'.format(grid_clf.best_params_, grid_clf.best_score_))
    best_model = grid_clf.best_estimator_
    y_pred = best_model.predict(X_test)
    y_pred_proba = best_model.predict_proba(X_test)[:, 1]
    evaluation(y_test, y_pred, y_pred_proba)

In [15]:
scale_method = ['None', 'Standard', 'MinMax', 'Log']

cancer = load_breast_cancer()
X_train, X_test, y_train, y_test = train_test_split(cancer.data, cancer.target, test_size=0.3)

params = {
    'penalty': ['l1', 'l2'],
    'C': [0.01, 0.05, 0.1, 1, 5, 10],
}

for s in scale_method:
    X_scaled_train, X_scaled_test = scale(s, X_train, X_test)
    print("Scaled Method:", s)
    lr_clf = LogisticRegression(solver='liblinear', max_iter=1000)
    Search(lr_clf, X_scaled_train, X_scaled_test, y_train, y_test, params)

Scaled Method: None
최적 하이퍼 파라미터 : {'C': 10, 'penalty': 'l1'}, 최적 평균 정확도 0.955
오차 행렬
[[67  5]
 [ 0 99]]
정확도 : 0.9708 정밀도 0.9519 재현율 1.0000 F1 0.9754 AUC 0.9994

Scaled Method: Standard
최적 하이퍼 파라미터 : {'C': 0.05, 'penalty': 'l2'}, 최적 평균 정확도 0.977
오차 행렬
[[67  5]
 [ 0 99]]
정확도 : 0.9708 정밀도 0.9519 재현율 1.0000 F1 0.9754 AUC 0.9969

Scaled Method: MinMax
최적 하이퍼 파라미터 : {'C': 10, 'penalty': 'l1'}, 최적 평균 정확도 0.972
오차 행렬
[[69  3]
 [ 1 98]]
정확도 : 0.9766 정밀도 0.9703 재현율 0.9899 F1 0.9800 AUC 0.9966

Scaled Method: Log
최적 하이퍼 파라미터 : {'C': 10, 'penalty': 'l1'}, 최적 평균 정확도 0.955
오차 행렬
[[66  6]
 [ 0 99]]
정확도 : 0.9649 정밀도 0.9429 재현율 1.0000 F1 0.9706 AUC 0.9983

